Areas/Admin/Controllers/ThongKeController.cs
using Electro.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Electro.Areas.Admin.Controllers
{
    public class ThongKeController : Controller
    {
        ElectroDbContext db = new ElectroDbContext();
        // GET: Admin/ThongKe



        [HttpGet]
        public ActionResult SanPhamBanChay()
        {
            var ToDay = DateTime.Now.Date;
            var lstSP = GetListSPBC(ToDay, ToDay);

            ViewBag.TuNgay = ToDay;
            ViewBag.DenNgay = ToDay;
            return View(lstSP);
        }

        [HttpPost]
        public ActionResult SanPhamBanChay(FormCollection f)
        {

            DateTime TuNgay;
            DateTime DenNgay;
            bool flagHasError = false;


            if (DateTime.TryParse(f["TuNgay"], out TuNgay))
            {
                TuNgay = Convert.ToDateTime(f["TuNgay"]);
            }
            else
            {
                ViewBag.KiemTraNgayBatDau = "Ngày bắt đầu không hợp lệ";
                flagHasError = true;
            }



            if (DateTime.TryParse(f["DenNgay"], out DenNgay))
            {
                DenNgay = Convert.ToDateTime(f["DenNgay"]);
            }
            else
            {
                ViewBag.KiemTraNgayKetThuc = "Ngày đến không hợp lệ";
                flagHasError = true;
            }

            DateTime ToDay = DateTime.Now.Date;
            var lstDDHx = GetListSPBC(ToDay, ToDay);
            ViewBag.SoLuong = lstDDHx.Count();
            ViewBag.TongTien = 0;
            ViewBag.TuNgay = ToDay;
            ViewBag.DenNgay = ToDay;
            if (flagHasError == true)
            {

                return View(lstDDHx);
            }

            if (TuNgay > DenNgay)
            {
                ViewBag.KiemTraNgayKetThuc = "Ngày kết thúc không được nhỏ hơn ngày bắt đầu.";
                return View(lstDDHx);
            }







 
            var lstSP = GetListSPBC(TuNgay, DenNgay);

            ViewBag.TuNgay = TuNgay;
            ViewBag.DenNgay = DenNgay;
            return View(lstSP);
        }
        public IEnumerable<Electro.Models.TakeEverything> GetListSPBC(DateTime TuNgay, DateTime DenNgay)
        {
            var lstSP = (from ctdh in db.ChiTietDonDatHangs
                         join ddh in db.DonDatHangs on ctdh.MaDDH equals ddh.MaDDH
                         where (ddh.NgayLap >= TuNgay && ddh.NgayLap <= DenNgay)
                         group ctdh by ctdh.MaSP into s
                         select new TakeEverything
                         {
                             MaSP = s.Key,
                             SoLuongBan = s.Sum(n => n.SoLuong),
                             TenSP = s.Select(n => n.TenSP).FirstOrDefault()
                         }).OrderByDescending(n => n.SoLuongBan);
            return lstSP;

        }

        public ActionResult SanPhamHetHang(int? page)
        {
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Admin");

            }

            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            var lst = db.SanPhams.Where(n => n.SoLuongTon == 0).ToList().OrderBy(n => n.MaSP).ToPagedList(iPageNum, iPageSize);
            return View(lst);
        }
    }
}

Areas/Admin/Views/ThongKe/SanPhamBanChay.cshtml
@model IEnumerable<Electro.Models.TakeEverything>

@{
    ViewBag.Title = "SanPhamBanChay";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sản phẩm bán chạy</h2>
@ViewBag.TuNgay
<div class="container">

    @using (Html.BeginForm("SanPhamBanChay", "ThongKe", FormMethod.Post))
    {
        <div class="form-group" style="text-align:center">
            <div class="col-md-10">
                <lable>Từ:</lable>
                <input type="date" name="TuNgay" value="@Html.FormatValue(ViewBag.TuNgay , "{0:yyyy-MM-dd}")" />
                <lable>Đến:</lable>
                <input type="date" name="DenNgay"
                       value="@Html.FormatValue(ViewBag.DenNgay , "{0:yyyy-MM-dd}")" />
                <button id="btnLocBanChay" type="submit">Lọc</button>
            </div>

            @if (string.IsNullOrEmpty(ViewBag.KiemTraNgayKetThuc) || string.IsNullOrEmpty(ViewBag.KiemTraNgayBatDau))
            {<div class="col-md-10">
                    <p id="NgayBatDau" style="color:red; text-align:center">@ViewBag.KiemTraNgayBatDau</p>
                    <p id="NgayKetThuc" style="color:red; text-align:center">@ViewBag.KiemTraNgayKetThuc</p>
                </div>
            }
        </div>

    }

    <div class="col-md-12">
        <table class="table-hover">

            <tr style="background-color:darkgray">
                <th style="text-align:center; width:30%">
                    Mã sản phẩm
                </th>
                <th style="text-align:center; width:60%">
                    Tên sản phẩm
                </th>
                <th style="text-align:center; width:10%">
                    Số lượng bán
                </th>
                <th style="text-align:center"></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td style="text-align:center;">
                        @item.MaSP
                    </td>
                    <td style="text-align:center">
                        @item.TenSP
                    </td>
                    <td style="text-align:center">
                        @item.SoLuongBan
                    </td>
                </tr>
            }

        </table>
    </div>

</div>
<br />

Areas/Admin/Views/ThongKe/SanPhamHetHang.cshtml
@model PagedList.PagedList<Electro.Models.SanPham>
@using PagedList.Mvc
@using Electro.Models



@*Tao helper rieng*@
@helper TrunCate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>....</text>
    }
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <h2 style="text-align:center">Danh sách sản phẩm</h2>

    <table class="table-hover">
        <tr style="background-color:darkgray">
            <th style="text-align:center; width:2%">
                Mã
            </th>
            <th style="text-align:center; width:10%">
                Tên SP
            </th>
            <th style="text-align:center; width:15%">
                Cấu hình
            </th>
            <th style="text-align:center; width:10%">
                Ảnh
            </th>
            <th style="text-align:center; width:15%">
                Mô tả
            </th>

            <th style="text-align:center; width:6%">
                Ngày cập nhật
            </th>
            <th style="text-align:center; width:5%">
                Số lượng
            </th>
            <th style="text-align:center; width:5%">
                Giá bán
            </th>
            <th style="text-align:center; width:4%">
                Lượt xem
            </th>
            <th style="text-align:center; width:4%">
                Đánh giá
            </th>
            <th style="text-align:center; width:10%">
                Nhà cung cấp
            </th>
            <th style="text-align:center; width:5%">
                Thương hiệu
            </th>
            <th style="text-align:center"></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center; font-weight:bold">
                    @item.MaSP
                </td>
                <td style="text-align:center">
                    <a href="@Url.Action("ChiTiet", new { MaSP = item.MaSP , url = Request.Url.ToString()})" style="color:black">
                        @TrunCate(item.TenSP, 20)
                    </a>
                </td>
                <td style="text-align:left">
                    @Html.Raw(TrunCate(item.CauHinh, 50).ToString())
                </td>
                <td style="text-align:center">
                    <img src="~/img/@item.HinhAnh" style="width:70px" />
                </td>
                <td style="text-align:left">
                    @Html.Raw(TrunCate(item.MoTa, 30).ToString())
                </td>

                <td style="text-align:center">
                    @Html.FormatValue(item.NgayCapNhat, "{0:dd/MM/yyyy}")
                </td>
                <td style="text-align:center">
                    @item.SoLuongTon
                </td>
                <td style="text-align:center">
                    @Html.FormatValue(item.DonGia, "{0:#,##0}")
                </td>
                <td style="text-align:center">
                    @item.LuotXem
                </td>
                <td style="text-align:center">
                    @item.TrungBinhDanhGia
                </td>

                <td style="text-align:center">
                    @item.NhaCungCap.TenNCC
                </td>
                <td style="text-align:center">
                    @item.NhaSanXuat.TenNSX
                </td>

            </tr>
        }

    </table>

    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))

    </div>

</div>
<style>
    .MenuTrang {
        display: inline;
        display: inline;
        text-align: center;
    }
</style>