Controllers/DanhGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Electro.Models;
using PagedList.Mvc;
using PagedList;
namespace Electro.Controllers
{
    
    public class DanhGiaController : Controller
    {
        ElectroDbContext db = new ElectroDbContext();
        private void UpdateTrungBinhDanhGia(int MaSP)
        {
            SanPham sp = db.SanPhams.Single(n => n.MaSP == MaSP);
            int SoLuongDanhGia = db.BinhLuans.Count(n => n.MaSP == MaSP);
            int TongDanhGia = (int)(from bl in db.BinhLuans where bl.MaSP == MaSP select bl).Sum(n => n.DanhGia);
            if (SoLuongDanhGia != 0)
                sp.TrungBinhDanhGia = (TongDanhGia * 10 / SoLuongDanhGia) / 10;
            else
                sp.TrungBinhDanhGia = 0;
            db.SaveChanges();
        }
        // GET: DanhGia
        public ActionResult Index(int MaSP, double ? GiaSale, int? Page, bool hasError = false)
        {
            ViewBag.GiaSale = GiaSale;
            ViewBag.MaSP = MaSP;
            ViewBag.Page = Page;
            ViewBag.CoLoi = hasError;
            return View();
        }
        public ActionResult RatingPartial(int MaSP)
        {
            ViewBag.SoLuongDanhGia = db.BinhLuans.Count(n => n.MaSP == MaSP);
            ViewBag.TongDanhGia = (from bl in db.BinhLuans where bl.MaSP == MaSP select bl).Sum(n => n.DanhGia);
            var DanhGia = from bl in db.BinhLuans where bl.MaSP == MaSP
                          group bl by bl.DanhGia into dg
                          select new TakeEverything
                          {
                              SoSao = (int)dg.Key,
                              SoLuongDanhGia = dg.Count()
                          };
            return PartialView(DanhGia);
        }
        public ActionResult ReviewPartial(int MaSP, double? GiaSale, int ? Page)
        {
            ViewBag.GiaSale = GiaSale;
            ViewBag.MaSP = MaSP;
            int iPageNum = (Page ?? 1);
            var ListBinhLuan = (from bl in db.BinhLuans where bl.MaSP == MaSP select bl).OrderByDescending(n => n.MaBinhLuan).ToList();
            return PartialView(ListBinhLuan.ToPagedList(iPageNum, 3));
        }
        [HttpGet]
        public ActionResult ReviewFormPartial(int MaSP, double ? GiaSale)
        {
            ViewBag.MaSP = MaSP;
            ViewBag.GiaSale = GiaSale;

            if(KiemTraThongTin.hasError == true)
            {
                ViewBag.KiemTraHoTen = KiemTraThongTin.hasErrorHoTen;
                ViewBag.KiemTraEmail = KiemTraThongTin.hasErrorEmail;
                ViewBag.KiemTraBinhLuan = KiemTraThongTin.hasErrorBinhLuan;
                ViewBag.KiemTraRating = KiemTraThongTin.hasErrorRating;

            }
            KiemTraThongTin.hasError = false;


            
            return PartialView();
        }
        [HttpPost]
        public ActionResult ReviewFormPartial(FormCollection f)
        {
            string Email = f["Email"];
            string HoTen = f["HoTen"];
            string NoiDung = f["NoiDung"];
            int MaSP = Int32.Parse(f["MaSP"]);
            double GiaSale = Double.Parse(f["GiaSale"]);
            int DanhGia = string.IsNullOrEmpty(f["Rating"]) ? 0 : Int32.Parse(f["Rating"]);
            BinhLuan bl = new BinhLuan();
            bl.Email = Email;
            bl.MaSP = MaSP;
            bl.NguoiBinhLuan = HoTen;
            bl.NoiDung = NoiDung;
            bl.DanhGia = DanhGia;
            bl.NgayBinhLuan = DateTime.Now;

            bool flagHasError = false;

            //Kiểm tra họ tên
            if (string.IsNullOrEmpty(HoTen))
            {
                KiemTraThongTin.hasErrorHoTen = KiemTraThongTin.HOTEN_NULL;
                flagHasError = true;
            }
            else
            {
                KiemTraThongTin.hasErrorHoTen = "";
            }

            string resCheckEmail = KiemTraThongTin.KiemTraEmail(bl.Email);

            // Kiểm tra email
            if(resCheckEmail != "ok")
            {
                KiemTraThongTin.hasErrorEmail = resCheckEmail;
                flagHasError = true;
            }
            else
            {
                KiemTraThongTin.hasErrorEmail = "";
            }

            //Kiểm tra nội dung
            if (string.IsNullOrEmpty(bl.NoiDung))
            {
                KiemTraThongTin.hasErrorBinhLuan = "Nội dung không được để trống.";
                flagHasError = true;
            }
            else
            {
                KiemTraThongTin.hasErrorBinhLuan = "";
            }

            //Kiểm tra rating
            if (string.IsNullOrEmpty(f["Rating"])){
                KiemTraThongTin.hasErrorRating = "Rating không được để trống.";
                flagHasError = true;
            }
            else
            {
                KiemTraThongTin.hasErrorRating = "";
            }

            if(flagHasError == true)
            {
                KiemTraThongTin.hasError = true;
                return RedirectToAction("ChiTietSanPham", "Home", new { MaSP = MaSP, GiaSale = GiaSale});
            }
            KiemTraThongTin.hasError = false;
            

            db.BinhLuans.Add(bl);
            db.SaveChanges();
            UpdateTrungBinhDanhGia(MaSP);
            return RedirectToAction("ChiTietSanPham", "Home", new { MaSP = MaSP, GiaSale = GiaSale });
        }
    }
}

Views/DanhGia/Index.cshtml
<div class="row">
    <!-- Rating -->
    @Html.Action("RatingPartial", "DanhGia", new { MaSP = @ViewBag.MaSP })
    <!-- /Rating -->
    <!-- Reviews -->
    @Html.Action("ReviewPartial", "DanhGia", new { MaSP = @ViewBag.MaSP, GiaSale = ViewBag.GiaSale, Page = ViewBag.Page })
    <!-- /Reviews -->
    <!-- Review Form -->
     @Html.Action("ReviewFormPartial", "DanhGia", new { MaSP = @ViewBag.MaSP, GiaSale = ViewBag.GiaSale}) }
     <!-- /Review Form -->
</div>

Views/DanhGia/RatingPartial.cshtml
@model IEnumerable<Electro.Models.TakeEverything>

@{ 
    double TrungBinhDanhGia = 0;
    if (ViewBag.SoLuongDanhGia != 0)
    {
        TrungBinhDanhGia = Math.Round((double)(1.0 * ViewBag.TongDanhGia * 10 / ViewBag.SoLuongDanhGia));
    }

    TrungBinhDanhGia /= 10;
}
<div class="col-md-3">
    <div id="rating">
        <div class="rating-avg">
            
            <div class="rating-stars">
                @{ int star = 0;}
                @for (; star < @Math.Floor((double)TrungBinhDanhGia); star++)
                {
                    <i class="fa fa-star" style="color:orange"></i>

                }
                @if (star < @Math.Ceiling((double)TrungBinhDanhGia))
                {
                    <i class="fa fa-star-half-full" style="color:orange"></i>
                    star++;
                }
                @for (; star < 5; star++)
                {
                    <span class="fa fa-star-o"></span>
                }
            </div>
            <span style="color: orange; font-weight: bold; font-size:18px">@TrungBinhDanhGia</span>
        </div>
        <ul class="rating">
            @for (int i = 0; i < 5; i++)
            {
                
                int DanhGia = 0;
                foreach(var dg in Model)
                {
                    if(5 - i == dg.SoSao)
                    {
                        DanhGia = dg.SoLuongDanhGia;
                        break;
                    }
                }
                int TiLe = (int)Math.Round(1.0 * DanhGia*100 / ViewBag.SoLuongDanhGia);
                <li>
                    <div class="rating-stars">
                        @{int j = 0;}
                        @for (; j < 5 - i; j++)
                        {
                            <i class="fa fa-star"></i>
                        }
                        @for(int k = 0; k < 5-j; k++)
                        {
                            <i class="fa fa-star-o"></i>
                        }
                    </div>
                    <div class="rating-progress">
                        <div style="width: @TiLe%"></div>
                    </div>
                    <span class="sum">@DanhGia</span>

                 </li>
            }
        </ul>
    </div>
</div>

Views/DanhGia/ReviewFormPartial.cshtml
@{
    double GiaSale = 0;
    if (ViewBag.GiaSale != null)
    {
        GiaSale = @ViewBag.GiaSale;
    }

}

<div class="col-md-3">
    <div id="review-form">
        @using (Html.BeginForm("ReviewFormPartial", "DanhGia", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "review-form" }))
        {
            if (!string.IsNullOrEmpty(ViewBag.KiemTraHoTen))
            {
                <p id="KTHoTen" style="color:red">@ViewBag.KiemTraHoTen </p>
            }
            <input class="input"
                   type="text"
                   placeholder="Your Name" name="HoTen" />


            if (!string.IsNullOrEmpty(ViewBag.KiemTraEmail))
            {
                <p id="KTEmail" style="color:red">@ViewBag.KiemTraEmail </p>
            }
            <input class="input"
                   type="text"
                   placeholder="Your Email" name="Email" />

            if (!string.IsNullOrEmpty(ViewBag.KiemTraBinhLuan))
            {
                <p id="KTNoiDung" style="color:red">@ViewBag.KiemTraBinhLuan </p>
            }
            <textarea class="input"
                      placeholder="Your Review" name="NoiDung"></textarea>

            if (!string.IsNullOrEmpty(ViewBag.KiemTraRating))
            {
                <p id="KTRating" style="color:red">@ViewBag.KiemTraRating </p>
            }
            <div class="input-rating" id="emdepqua">
                <span>Your Rating: </span>
                <div class="stars" id="emkhungqua">
                    <input id="star5"
                           name="Rating"
                           value="5"
                           type="radio" /><label for="star5"></label>
                    <input id="star4"
                           name="Rating"
                           value="4"
                           type="radio" /><label for="star4"></label>
                    <input id="star3"
                           name="Rating"
                           value="3"
                           type="radio" /><label for="star3"></label>
                    <input id="star2"
                           name="Rating"
                           value="2"
                           type="radio" /><label for="star2"></label>
                    <input id="star1"
                           name="Rating"
                           value="1"
                           type="radio" /><label for="star1"></label>
                    <input type="hidden" name="MaSP" value="@ViewBag.MaSP" />
                    <input type="hidden" name="GiaSale" value="@GiaSale" />
                </div>
            </div>
            <button class="primary-btn">Submit</button>

        }
    </div>
</div>

Views/DanhGia/ReviewPartial.cshtml
@using Electro.Models;
@using PagedList.Mvc
@model PagedList.PagedList<BinhLuan>
<div class="col-md-6">
    <div id="reviews" class="tab-content">
        <ul class="reviews">
            @foreach (var bl in Model)
            {
                <li>
                    <div class="review-heading">
                        <h5 class="name">@bl.NguoiBinhLuan</h5>
                        <p class="date">@bl.NgayBinhLuan.Value.ToString("D")</p>
                        @{ int i = 0;}

                        <div class="review-rating">
                            @for (; i < bl.DanhGia; i++)
                            {
                                <i class="fa fa-star"></i>
                            }
                            @for (; i < 5; i++)
                            {
                                <i class="fa fa-star-o empty"></i>
                            }
                        </div>
                    </div>
                    <div class="review-body">
                        <p>
                            @bl.NoiDung
                        </p>
                    </div>
                </li>
            }
        </ul>

        Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("ChiTietSanPham", "Home", new { MaSP = ViewBag.MaSP,GiaSale = ViewBag.GiaSale, page = page }))
        </div>
        <style>
            .MenuTrang {
                display: inline;
                text-align: center;
            }
        </style>
    </div>
</div>